repos:
  - repo: https://github.com/pre-commit/mirrors-yapf/
    rev: v0.30.0
    hooks:
      - id: yapf
        files: ^(verval|tests)/.*\.py$
        args:
          - --diff
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        args:
          - --ignore=E501
  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        files: ^verval/.*\.py$
        args:
          - --errors-only
          - --disable=import-error
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.770"
    hooks:
      - id: mypy
        files: ^verval/.*\.py$
